language: julia
os:
  - osx
  - linux
julia:
  - 0.6
  - nightly
notifications:
  email: false

matrix:
  allow_failures:
  - julia: nightly

# Required for Dierckx
addons:
  apt:
    packages:
    - gfortran

before_install:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
            brew cask uninstall oclint;
            brew install gcc;
      fi

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("SAC"); Pkg.test("SAC"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("SAC")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
